// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/signup": {
    params: {};
  };
  "/auth/verify-email": {
    params: {};
  };
  "/auth/forgot-password": {
    params: {};
  };
  "/auth/reset-password": {
    params: {};
  };
  "/auth/confirm": {
    params: {};
  };
  "/auth/signout": {
    params: {};
  };
  "/onboarding/welcome": {
    params: {};
  };
  "/onboarding/profile": {
    params: {};
  };
  "/onboarding/upload": {
    params: {};
  };
  "/onboarding/first-recommendation": {
    params: {};
  };
  "/onboarding/complete": {
    params: {};
  };
  "/recover-account": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/wardrobe": {
    params: {};
  };
  "/wardrobe/add": {
    params: {};
  };
  "/wardrobe/analyze": {
    params: {};
  };
  "/wardrobe/:itemId": {
    params: {
      "itemId": string;
    };
  };
  "/outfits": {
    params: {};
  };
  "/outfits/create": {
    params: {};
  };
  "/outfits/collections/:collectionId": {
    params: {
      "collectionId": string;
    };
  };
  "/outfits/collections/:collectionId/edit": {
    params: {
      "collectionId": string;
    };
  };
  "/outfits/:outfitId": {
    params: {
      "outfitId": string;
    };
  };
  "/wardrobe/analytics": {
    params: {};
  };
  "/trends": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/api/image-url": {
    params: {};
  };
  "/api/upload-photo": {
    params: {};
  };
  "/api/remove-avatar": {
    params: {};
  };
  "/api/remove-tryon": {
    params: {};
  };
  "/api/recommendations/interact": {
    params: {};
  };
  "/api/sync-trends": {
    params: {};
  };
  "/api/items/:itemId/favorite": {
    params: {
      "itemId": string;
    };
  };
  "/api/items/:itemId/worn": {
    params: {
      "itemId": string;
    };
  };
  "/api/items/:itemId/archive": {
    params: {
      "itemId": string;
    };
  };
  "/api/items/wear-history": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth/login" | "/auth/signup" | "/auth/verify-email" | "/auth/forgot-password" | "/auth/reset-password" | "/auth/confirm" | "/auth/signout" | "/onboarding/welcome" | "/onboarding/profile" | "/onboarding/upload" | "/onboarding/first-recommendation" | "/onboarding/complete" | "/recover-account" | "/dashboard" | "/wardrobe" | "/wardrobe/add" | "/wardrobe/analyze" | "/wardrobe/:itemId" | "/outfits" | "/outfits/create" | "/outfits/collections/:collectionId" | "/outfits/collections/:collectionId/edit" | "/outfits/:outfitId" | "/wardrobe/analytics" | "/trends" | "/profile" | "/settings" | "/api/image-url" | "/api/upload-photo" | "/api/remove-avatar" | "/api/remove-tryon" | "/api/recommendations/interact" | "/api/sync-trends" | "/api/items/:itemId/favorite" | "/api/items/:itemId/worn" | "/api/items/:itemId/archive" | "/api/items/wear-history" | "/*";
  };
  "routes/guest._layout.tsx": {
    id: "routes/guest._layout";
    page: "/";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth._layout.tsx": {
    id: "routes/auth._layout";
    page: "/auth/login" | "/auth/signup" | "/auth/verify-email" | "/auth/forgot-password" | "/auth/reset-password" | "/auth/confirm" | "/auth/signout";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/auth/login";
  };
  "routes/auth/signup.tsx": {
    id: "routes/auth/signup";
    page: "/auth/signup";
  };
  "routes/auth/verify-email.tsx": {
    id: "routes/auth/verify-email";
    page: "/auth/verify-email";
  };
  "routes/auth/forgot-password.tsx": {
    id: "routes/auth/forgot-password";
    page: "/auth/forgot-password";
  };
  "routes/auth/reset-password.tsx": {
    id: "routes/auth/reset-password";
    page: "/auth/reset-password";
  };
  "routes/auth/confirm.tsx": {
    id: "routes/auth/confirm";
    page: "/auth/confirm";
  };
  "routes/auth/signout.ts": {
    id: "routes/auth/signout";
    page: "/auth/signout";
  };
  "routes/onboarding._layout.tsx": {
    id: "routes/onboarding._layout";
    page: "/onboarding/welcome" | "/onboarding/profile" | "/onboarding/upload" | "/onboarding/first-recommendation" | "/onboarding/complete";
  };
  "routes/onboarding/welcome.tsx": {
    id: "routes/onboarding/welcome";
    page: "/onboarding/welcome";
  };
  "routes/onboarding/profile.tsx": {
    id: "routes/onboarding/profile";
    page: "/onboarding/profile";
  };
  "routes/onboarding/upload.tsx": {
    id: "routes/onboarding/upload";
    page: "/onboarding/upload";
  };
  "routes/onboarding/first-recommendation.tsx": {
    id: "routes/onboarding/first-recommendation";
    page: "/onboarding/first-recommendation";
  };
  "routes/onboarding/complete.tsx": {
    id: "routes/onboarding/complete";
    page: "/onboarding/complete";
  };
  "routes/recover-account.tsx": {
    id: "routes/recover-account";
    page: "/recover-account";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/dashboard" | "/wardrobe" | "/wardrobe/add" | "/wardrobe/analyze" | "/wardrobe/:itemId" | "/outfits" | "/outfits/create" | "/outfits/collections/:collectionId" | "/outfits/collections/:collectionId/edit" | "/outfits/:outfitId" | "/wardrobe/analytics" | "/trends" | "/profile" | "/settings";
  };
  "routes/dashboard/_index.tsx": {
    id: "routes/dashboard/_index";
    page: "/dashboard";
  };
  "routes/wardrobe/_index.tsx": {
    id: "routes/wardrobe/_index";
    page: "/wardrobe";
  };
  "routes/wardrobe/add.tsx": {
    id: "routes/wardrobe/add";
    page: "/wardrobe/add";
  };
  "routes/wardrobe/analyze.tsx": {
    id: "routes/wardrobe/analyze";
    page: "/wardrobe/analyze";
  };
  "routes/wardrobe/$itemId.tsx": {
    id: "routes/wardrobe/$itemId";
    page: "/wardrobe/:itemId";
  };
  "routes/outfits/_index.tsx": {
    id: "routes/outfits/_index";
    page: "/outfits";
  };
  "routes/outfits/create.tsx": {
    id: "routes/outfits/create";
    page: "/outfits/create";
  };
  "routes/outfits/collections.$collectionId.tsx": {
    id: "routes/outfits/collections.$collectionId";
    page: "/outfits/collections/:collectionId";
  };
  "routes/outfits/collections.$collectionId.edit.tsx": {
    id: "routes/outfits/collections.$collectionId.edit";
    page: "/outfits/collections/:collectionId/edit";
  };
  "routes/outfits/$outfitId.tsx": {
    id: "routes/outfits/$outfitId";
    page: "/outfits/:outfitId";
  };
  "routes/wardrobe.analytics.tsx": {
    id: "routes/wardrobe.analytics";
    page: "/wardrobe/analytics";
  };
  "routes/trends/_index.tsx": {
    id: "routes/trends/_index";
    page: "/trends";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/api/image-url.ts": {
    id: "routes/api/image-url";
    page: "/api/image-url";
  };
  "routes/api/upload-photo.ts": {
    id: "routes/api/upload-photo";
    page: "/api/upload-photo";
  };
  "routes/api/remove-avatar.ts": {
    id: "routes/api/remove-avatar";
    page: "/api/remove-avatar";
  };
  "routes/api/remove-tryon.ts": {
    id: "routes/api/remove-tryon";
    page: "/api/remove-tryon";
  };
  "routes/api/recommendations/interact.ts": {
    id: "routes/api/recommendations/interact";
    page: "/api/recommendations/interact";
  };
  "routes/api/sync-trends.ts": {
    id: "routes/api/sync-trends";
    page: "/api/sync-trends";
  };
  "routes/api/items/$itemId/favorite.ts": {
    id: "routes/api/items/$itemId/favorite";
    page: "/api/items/:itemId/favorite";
  };
  "routes/api/items/$itemId/worn.ts": {
    id: "routes/api/items/$itemId/worn";
    page: "/api/items/:itemId/worn";
  };
  "routes/api/items/$itemId/archive.ts": {
    id: "routes/api/items/$itemId/archive";
    page: "/api/items/:itemId/archive";
  };
  "routes/api/items/wear-history.ts": {
    id: "routes/api/items/wear-history";
    page: "/api/items/wear-history";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/guest._layout": typeof import("./app/routes/guest._layout.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/auth._layout": typeof import("./app/routes/auth._layout.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/signup": typeof import("./app/routes/auth/signup.tsx");
  "routes/auth/verify-email": typeof import("./app/routes/auth/verify-email.tsx");
  "routes/auth/forgot-password": typeof import("./app/routes/auth/forgot-password.tsx");
  "routes/auth/reset-password": typeof import("./app/routes/auth/reset-password.tsx");
  "routes/auth/confirm": typeof import("./app/routes/auth/confirm.tsx");
  "routes/auth/signout": typeof import("./app/routes/auth/signout.ts");
  "routes/onboarding._layout": typeof import("./app/routes/onboarding._layout.tsx");
  "routes/onboarding/welcome": typeof import("./app/routes/onboarding/welcome.tsx");
  "routes/onboarding/profile": typeof import("./app/routes/onboarding/profile.tsx");
  "routes/onboarding/upload": typeof import("./app/routes/onboarding/upload.tsx");
  "routes/onboarding/first-recommendation": typeof import("./app/routes/onboarding/first-recommendation.tsx");
  "routes/onboarding/complete": typeof import("./app/routes/onboarding/complete.tsx");
  "routes/recover-account": typeof import("./app/routes/recover-account.tsx");
  "routes/_layout": typeof import("./app/routes/_layout.tsx");
  "routes/dashboard/_index": typeof import("./app/routes/dashboard/_index.tsx");
  "routes/wardrobe/_index": typeof import("./app/routes/wardrobe/_index.tsx");
  "routes/wardrobe/add": typeof import("./app/routes/wardrobe/add.tsx");
  "routes/wardrobe/analyze": typeof import("./app/routes/wardrobe/analyze.tsx");
  "routes/wardrobe/$itemId": typeof import("./app/routes/wardrobe/$itemId.tsx");
  "routes/outfits/_index": typeof import("./app/routes/outfits/_index.tsx");
  "routes/outfits/create": typeof import("./app/routes/outfits/create.tsx");
  "routes/outfits/collections.$collectionId": typeof import("./app/routes/outfits/collections.$collectionId.tsx");
  "routes/outfits/collections.$collectionId.edit": typeof import("./app/routes/outfits/collections.$collectionId.edit.tsx");
  "routes/outfits/$outfitId": typeof import("./app/routes/outfits/$outfitId.tsx");
  "routes/wardrobe.analytics": typeof import("./app/routes/wardrobe.analytics.tsx");
  "routes/trends/_index": typeof import("./app/routes/trends/_index.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/api/image-url": typeof import("./app/routes/api/image-url.ts");
  "routes/api/upload-photo": typeof import("./app/routes/api/upload-photo.ts");
  "routes/api/remove-avatar": typeof import("./app/routes/api/remove-avatar.ts");
  "routes/api/remove-tryon": typeof import("./app/routes/api/remove-tryon.ts");
  "routes/api/recommendations/interact": typeof import("./app/routes/api/recommendations/interact.ts");
  "routes/api/sync-trends": typeof import("./app/routes/api/sync-trends.ts");
  "routes/api/items/$itemId/favorite": typeof import("./app/routes/api/items/$itemId/favorite.ts");
  "routes/api/items/$itemId/worn": typeof import("./app/routes/api/items/$itemId/worn.ts");
  "routes/api/items/$itemId/archive": typeof import("./app/routes/api/items/$itemId/archive.ts");
  "routes/api/items/wear-history": typeof import("./app/routes/api/items/wear-history.ts");
  "routes/$": typeof import("./app/routes/$.tsx");
};